# Generated by Django 5.2.1 on 2025-06-13 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parameterset",
            name="battery_type",
        ),
        migrations.RemoveField(
            model_name="simulationtemplate",
            name="battery_type",
        ),
        migrations.AlterUniqueTogether(
            name="parameterset",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="parameterset",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="simulationrun",
            name="user",
        ),
        migrations.RemoveField(
            model_name="simulationshare",
            name="simulation",
        ),
        migrations.RemoveField(
            model_name="simulationshare",
            name="shared_by",
        ),
        migrations.RemoveField(
            model_name="simulationtemplate",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_used", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="APIUsage",
        ),
        migrations.DeleteModel(
            name="BatteryType",
        ),
        migrations.DeleteModel(
            name="ParameterSet",
        ),
        migrations.DeleteModel(
            name="SimulationRun",
        ),
        migrations.DeleteModel(
            name="SimulationShare",
        ),
        migrations.DeleteModel(
            name="SimulationTemplate",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
